name: Notify private course repository

on:
  push:
    branches:
      - main

jobs:
  dispatch:
    if: github.repository == 'MikkoP-Opetukset/rust-0603-use'
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch submodule update
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PRIVATE_REPO_PAT }}
          repository: MikkoP-Opetukset/ic00bj79-rust-programming
          event-type: update-submodules
